# DHCPv4 client configuration to test Arista AP ZTP.
# The vendor class is kept after the request policy for dhclient versions
# without the -V command-line option.

request subnet-mask, broadcast-address, time-offset, routers,
        domain-name, domain-name-servers, domain-search, host-name,
        vendor-encapsulated-options;

send vendor-class-identifier "ARISTA-AP-430";
