# DHCPv6 client config to test Arista AP C-430 ZTP
# Usage: dhclient -6 -cf dhclient6.conf -d -v <interface>

option dhcp6.vendor-class code 16 = string;

send dhcp6.vendor-class "\x00\x00\x42\x05\x00\x0f\x41\x52\x49\x53\x54\x41\x2d\x41\x50\x2d\x43\x2d\x34\x33\x30";

also request dhcp6.vendor-opts;
