option vendor-class-identifier code 60 = string;

option vendor-class-identifier "ARISTA-AP-430";

send vendor-class-identifier;


# request subnet-mask, broadcast-address, time-offset, routers,
#         domain-name, domain-name-servers, domain-search, host-name,
#         dhcp6.name-servers, dhcp6.domain-search, dhcp6.fqdn, dhcp6.sntp-servers,
#         netbios-name-servers, netbios-scope, interface-mtu,
#         rfc3442-classless-static-routes, ntp-servers,
#         vendor-encapsulated-options;