#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ──────────────────────────────────────────────
# Colors & Formatting
# ──────────────────────────────────────────────
if [[ -t 1 ]]; then
    BOLD='\033[1m'
    DIM='\033[2m'
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    CYAN='\033[0;36m'
    WHITE='\033[1;37m'
    RESET='\033[0m'
else
    BOLD='' DIM='' RED='' GREEN='' YELLOW='' CYAN='' WHITE='' RESET=''
fi

print_header()  { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }
print_success() { echo -e "  ${GREEN}[OK]${RESET} $1"; }
print_error()   { echo -e "  ${RED}[ERROR]${RESET} $1" >&2; }
print_warn()    { echo -e "  ${YELLOW}[WARN]${RESET} $1"; }
print_info()    { echo -e "  ${DIM}$1${RESET}"; }

banner() {
    echo -e "${BOLD}${CYAN}"
    cat <<'BANNER'
    _         _     _          __________  ____
   / \   _ __(_)___| |_ __ _  |__  /_   _|  _ \
  / _ \ | '__| / __| __/ _` |   / /  | | | |_) |
 / ___ \| |  | \__ \ || (_| |  / /_  | | |  __/
/_/   \_\_|  |_|___/\__\__,_| /____| |_| |_|
BANNER
    echo -e "${RESET}"
    echo -e "  ${DIM}Zero-Touch Provisioning for Arista Access Points${RESET}"
    echo -e "  ${DIM}Generates ISC DHCP server configurations for AP onboarding${RESET}"
    echo ""
}

# ──────────────────────────────────────────────
# Validation
# ──────────────────────────────────────────────
validate_ipv4() {
    local ip="$1"
    local IFS='.'
    read -ra octets <<< "$ip"
    [[ ${#octets[@]} -ne 4 ]] && return 1
    for octet in "${octets[@]}"; do
        [[ ! "$octet" =~ ^[0-9]+$ ]] && return 1
        (( octet < 0 || octet > 255 )) && return 1
    done
    return 0
}

validate_ipv6() {
    local ip="$1"
    [[ "$ip" =~ ^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}$ ]] || \
    [[ "$ip" =~ ^([0-9a-fA-F]{0,4}:){1,6}:[0-9a-fA-F]{0,4}$ ]] || \
    [[ "$ip" =~ :: ]]
}

validate_cidr_v4() {
    local cidr="$1"
    [[ "$cidr" =~ ^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/([0-9]+)$ ]] || return 1
    local ip="${BASH_REMATCH[1]}"
    local prefix="${BASH_REMATCH[2]}"
    validate_ipv4 "$ip" || return 1
    (( prefix < 0 || prefix > 32 )) && return 1
    return 0
}

validate_cidr_v6() {
    local cidr="$1"
    [[ "$cidr" =~ ^(.+)/([0-9]+)$ ]] || return 1
    local prefix="${BASH_REMATCH[2]}"
    (( prefix < 0 || prefix > 128 )) && return 1
    return 0
}

validate_netmask() {
    validate_ipv4 "$1" || return 1
    local IFS='.'
    read -ra o <<< "$1"
    local n=$(( (o[0] << 24) + (o[1] << 16) + (o[2] << 8) + o[3] ))
    local inv=$(( ~n & 0xFFFFFFFF ))
    (( (inv & (inv + 1)) == 0 )) && return 0
    return 1
}

# ──────────────────────────────────────────────
# CIDR Auto-Derivation (IPv4)
# ──────────────────────────────────────────────
cidr_to_netmask() {
    local prefix="$1"
    local mask=$(( 0xFFFFFFFF << (32 - prefix) & 0xFFFFFFFF ))
    printf "%d.%d.%d.%d" \
        $(( (mask >> 24) & 0xFF )) \
        $(( (mask >> 16) & 0xFF )) \
        $(( (mask >> 8)  & 0xFF )) \
        $(( mask & 0xFF ))
}

suggest_range() {
    local network="$1"
    local IFS='.'
    read -ra octets <<< "${network%%/*}"
    local base="${octets[0]}.${octets[1]}.${octets[2]}"
    echo "${base}.100 ${base}.200"
}

suggest_gateway() {
    local network="$1"
    local IFS='.'
    read -ra octets <<< "${network%%/*}"
    printf "%s.%s.%s.1" "${octets[0]}" "${octets[1]}" "${octets[2]}"
}

# ──────────────────────────────────────────────
# Config Generator (replaces Jinja2 template)
# ──────────────────────────────────────────────
generate_config() {
    local network_addr="${NETWORK%%/*}"

    cat <<EOF
###################
# isc-dhcp-server #
###################
# Generated by setup_arista_wifi_ztp.sh
# Author: benedikt@arista.com
# ISC DHCP Configuration for Arista ZTP
# CV-CUE Server: ${CVCUE}
#
EOF

    if [[ "$IPVERSION" == "6" ]]; then
        cat <<'EOF'
# For testing w/o Arista AP see isc-dhcp6-ap-client6.conf
# Doc: https://www.arista.com/en/ug-cv-cue/cv-cue-dhcp-ipv6-server-discovery-by-arista-access-points
#
# The RA from the router residing in AP NETWORK need to contain:
#   ipv6 nd other-config-flag
#   ipv6 nd managed-config-flag
#
# DHCPv6 Option 16 (We want to match on):
#   Byte 0-3:  Enterprise Number (4 bytes)  →  \x00\x00\x42\x05  (16901) (Arista)
#   Byte 4-5:  Data Length (2 bytes)         →  \x00\x0f          (15)
#   Byte 6-20: VCI String (15 bytes)         →  ARISTA-AP-C-430
# As we want only VCI, we need "substring" with offset 6 and taking 15 bytes
#
# DHCPv6 Option 17 (We want to return):
#   Byte 0-3:   Enterprise Number (4 bytes)   →  \x00\x00\x42\x05  (16901) (Arista)
#   Byte 4-5:   Sub-option 1 Code (2 bytes)   →  \x00\x01          (Server Address)
#   Byte 6-7:   Sub-option 1 Length (2 bytes)  →  \x00\x16          (22)
#   Byte 8-29:  Sub-option 1 Data (22 bytes)   →  fd12:3456:789a:40::100
#   Byte 30-31: Sub-option 4 Code (2 bytes)    →  \x00\x04          (Magic String)
#   Byte 32-33: Sub-option 4 Length (2 bytes)   →  \x00\x0b          (11)
#   Byte 34-44: Sub-option 4 Data (11 bytes)    →  SPECTRATALK
# To generate this byte string you can use isc-dhcp6-generate_option17.py
EOF
    fi

    cat <<'EOF'

# General
authoritative;
default-lease-time 3600;
preferred-lifetime 3600;
option dhcp-renewal-time 3600;
option dhcp-rebinding-time 7200;
EOF

    if [[ "$IPVERSION" == "4" ]]; then
        cat <<EOF

# Arista AP Onboarding

option space arista;
option arista.cv-cue-server code 1 = text;
option arista.magic-string code 4 = text;

class "Arista-AP" {
    match if option vendor-class-identifier ~= "${MATCHSTRING}";
    vendor-option-space arista;
    option arista.cv-cue-server "${CVCUE}";
    option arista.magic-string "SPECTRATALK";
}
EOF

        if [[ -n "$TFTP" ]]; then
            cat <<EOF

class "Arista-CCS" {
    match if substring(option vendor-class-identifier, 0, 6) = "Arista";
    option bootfile-name "http://${TFTP}/ztp.conf";
}

EOF
        fi

        cat <<EOF

subnet ${network_addr} netmask ${NETMASK} {
    range ${RANGESTART} ${RANGEEND};
    option routers ${GATEWAY};
    option domain-name-servers ${NAMESERVER};
}
EOF
    fi

    if [[ "$IPVERSION" == "6" ]]; then
        cat <<EOF

# Define the DHCPv6 Option 16 (Vendor)
option space ARISTA_AP;
option ARISTA_AP.device_management_address code 1 = string;
option ARISTA_AP.magic code 4 = string;
option dhcp6.vendor-opts code 17 = encapsulate ARISTA_AP;

# Define search domain and dns
option dhcp6.domain-search "aristanetworks.com, sjc.aristanetworks.com, pune.aristanetworks.com.";
option dhcp6.name-servers ${NAMESERVER};

subnet6 ${NETWORK} {
  range6 ${network_addr}100 ${network_addr}200;

  if substring(option dhcp6.vendor-class, 6, 15) ~= "${MATCHSTRING}" {
    option dhcp6.vendor-opts "${MAGICSTRING}";
    option dhcp6.bootfile-url "my-startup-config";
  }
}
EOF
    fi
}

# ──────────────────────────────────────────────
# Help
# ──────────────────────────────────────────────
show_help() {
    banner

    echo -e "${BOLD}USAGE${RESET}"
    echo -e "  $0 ${DIM}[options]${RESET}"
    echo -e "  $0 ${DIM}(no arguments = interactive mode)${RESET}"
    echo ""

    echo -e "${BOLD}GENERAL OPTIONS${RESET}"
    echo -e "  ${CYAN}-h, --help${RESET}                          Show this help message"
    echo -e "  ${CYAN}-i, --interactive${RESET}                   Launch guided interactive setup"
    echo -e "  ${CYAN}-ipversion${RESET}      ${DIM}<4|6>${RESET}                IP version"
    echo -e "  ${CYAN}-network${RESET}        ${DIM}<CIDR>${RESET}               Subnet for the DHCP pool (e.g. 192.168.10.0/24)"
    echo -e "  ${CYAN}-nameserver${RESET}     ${DIM}<IP>${RESET}                 DNS server address"
    echo -e "  ${CYAN}-cvcue${RESET}          ${DIM}<IP|cloud>${RESET}           CV-CUE server IP, or ${YELLOW}cloud${RESET} for Arista cloud"
    echo -e "  ${CYAN}-mode${RESET}           ${DIM}<generate|install|test>${RESET}"
    echo ""

    echo -e "${BOLD}IPv4 OPTIONS${RESET}"
    echo -e "  ${CYAN}-netmask${RESET}        ${DIM}<MASK>${RESET}               Subnet mask ${DIM}(auto-derived from CIDR if omitted)${RESET}"
    echo -e "  ${CYAN}-gateway${RESET}        ${DIM}<IP>${RESET}                 Default gateway ${DIM}(defaults to .1 of the network)${RESET}"
    echo -e "  ${CYAN}-range-begin${RESET}    ${DIM}<IP>${RESET}                 DHCP range start ${DIM}(defaults to .100)${RESET}"
    echo -e "  ${CYAN}-range-end${RESET}      ${DIM}<IP>${RESET}                 DHCP range end ${DIM}(defaults to .200)${RESET}"
    echo -e "  ${CYAN}-matchstring${RESET}    ${DIM}<PATTERN>${RESET}            VCI match pattern ${DIM}(default: ARISTA-AP*)${RESET}"
    echo -e "  ${CYAN}-tftp${RESET}           ${DIM}<IP>${RESET}                 TFTP server for CCS/DCS boot ${DIM}(optional)${RESET}"
    echo ""

    echo -e "${BOLD}IPv6 OPTIONS${RESET}"
    echo -e "  ${CYAN}-matchstring${RESET}    ${DIM}<PATTERN>${RESET}            VCI match pattern ${DIM}(default: ARISTA-AP-C-*)${RESET}"
    echo ""

    echo -e "${BOLD}MODES${RESET}"
    echo -e "  ${GREEN}generate${RESET}    Render config and print to stdout ${DIM}(default)${RESET}"
    echo -e "  ${YELLOW}install${RESET}     Write config to /etc/dhcp/ and restart isc-dhcp-server ${DIM}(Ubuntu only)${RESET}"
    echo -e "  ${CYAN}test${RESET}        Test DHCP and DNS connectivity ${DIM}(requires -interface)${RESET}"
    echo ""

    echo -e "${BOLD}EXAMPLES${RESET}"
    echo ""
    echo -e "  ${DIM}# Interactive guided setup${RESET}"
    echo -e "  $0"
    echo ""
    echo -e "  ${DIM}# IPv4 with auto-derived netmask and range${RESET}"
    echo -e "  $0 -ipversion 4 -network 192.168.51.0/24 \\"
    echo -e "     -nameserver 192.168.51.250 -cvcue 10.113.204.10"
    echo ""
    echo -e "  ${DIM}# IPv4 with explicit overrides${RESET}"
    echo -e "  $0 -ipversion 4 -network 192.168.51.0/24 \\"
    echo -e "     -netmask 255.255.255.0 -range-begin 192.168.51.100 \\"
    echo -e "     -range-end 192.168.51.200 -gateway 192.168.51.1 \\"
    echo -e "     -nameserver 192.168.51.250 -cvcue 10.113.204.10"
    echo ""
    echo -e "  ${DIM}# IPv6${RESET}"
    echo -e "  $0 -ipversion 6 -network fd12:100:100:40::/64 \\"
    echo -e "     -nameserver fd12:100:100:40::1 -cvcue fd12:100:100:40::100 \\"
    echo -e "     -matchstring 'ARISTA-AP-C-*'"
    echo ""
    echo -e "  ${DIM}# Use Arista cloud instead of on-prem CV-CUE${RESET}"
    echo -e "  $0 -ipversion 4 -network 10.0.0.0/24 \\"
    echo -e "     -nameserver 10.0.0.1 -cvcue cloud"
    echo ""
    exit 0
}

# ──────────────────────────────────────────────
# Interactive Prompts
# ──────────────────────────────────────────────
prompt_value() {
    local prompt_text="$1"
    local default_val="$2"
    local var_name="$3"
    local validator="$4"
    local required="${5:-true}"

    while true; do
        if [[ -n "$default_val" ]]; then
            echo -en "  ${BOLD}${prompt_text}${RESET} ${DIM}[${default_val}]${RESET}: "
        else
            echo -en "  ${BOLD}${prompt_text}${RESET}: "
        fi

        local input
        read -r input

        if [[ -z "$input" && -n "$default_val" ]]; then
            input="$default_val"
        fi

        if [[ -z "$input" && "$required" == "true" ]]; then
            print_error "This field is required."
            continue
        fi

        if [[ -n "$validator" && -n "$input" ]]; then
            if ! $validator "$input"; then
                print_error "Invalid format. Please try again."
                continue
            fi
        fi

        eval "export $var_name=\"$input\""
        return 0
    done
}

prompt_choice() {
    local prompt_text="$1"
    local options="$2"
    local default_val="$3"
    local var_name="$4"

    while true; do
        echo -en "  ${BOLD}${prompt_text}${RESET} ${DIM}(${options})${RESET} ${DIM}[${default_val}]${RESET}: "
        local input
        read -r input
        [[ -z "$input" ]] && input="$default_val"

        if [[ "$options" == *"$input"* ]]; then
            eval "export $var_name=\"$input\""
            return 0
        fi
        print_error "Please choose one of: ${options}"
    done
}

print_summary() {
    echo ""
    echo -e "${BOLD}${CYAN}┌─────────────────────────────────────────────┐${RESET}"
    echo -e "${BOLD}${CYAN}│           Configuration Summary             │${RESET}"
    echo -e "${BOLD}${CYAN}└─────────────────────────────────────────────┘${RESET}"
    echo ""

    local label_width=20
    print_row() {
        printf "  ${BOLD}%-${label_width}s${RESET} %s\n" "$1" "$2"
    }

    print_row "Mode:" "$MODE"
    print_row "IP Version:" "IPv${IPVERSION}"
    print_row "Network:" "$NETWORK"

    if [[ "$IPVERSION" == "4" ]]; then
        print_row "Netmask:" "$NETMASK"
        print_row "Gateway:" "$GATEWAY"
        print_row "DHCP Range:" "${RANGESTART} - ${RANGEEND}"
    fi

    print_row "Nameserver:" "$NAMESERVER"
    print_row "CV-CUE Server:" "$CVCUE"

    if [[ -n "$MATCHSTRING" ]]; then
        print_row "VCI Match:" "$MATCHSTRING"
    fi
    if [[ -n "$TFTP" ]]; then
        print_row "TFTP Server:" "$TFTP"
    fi
    echo ""
}

interactive_setup() {
    banner

    # --- Step 1: Mode ---
    print_header "Step 1: What would you like to do?"
    echo ""
    echo -e "  ${GREEN}generate${RESET}  Generate DHCP config and print to stdout"
    echo -e "  ${YELLOW}install${RESET}   Generate, write to disk, and restart isc-dhcp-server ${DIM}(Ubuntu only)${RESET}"
    echo -e "  ${CYAN}test${RESET}      Test DHCP and DNS connectivity on an existing setup"
    echo ""
    prompt_choice "Mode" "generate/install/test" "generate" "MODE"
    echo ""

    # --- Step 2: IP Version ---
    print_header "Step 2: IP Version"
    echo ""
    prompt_choice "Which IP version?" "4/6" "4" "IPVERSION"
    echo ""

    # --- Test mode: only needs interface ---
    if [[ "$MODE" == "test" ]]; then
        print_header "Step 3: Test Interface"
        echo ""
        prompt_value "Network interface to test on (e.g. ens18, eth0)" "" "INTERFACE"
        echo ""

        echo -en "  ${BOLD}Run test?${RESET} ${DIM}[Y/n]${RESET}: "
        read -r confirm
        if [[ "$confirm" =~ ^[Nn] ]]; then
            print_warn "Aborted."
            exit 0
        fi
        return
    fi

    # --- Step 3: Network Configuration ---
    print_header "Step 3: Network Configuration"
    echo ""

    if [[ "$IPVERSION" == "4" ]]; then
        prompt_value "Subnet (CIDR notation, e.g. 192.168.10.0/24)" "" "NETWORK" "validate_cidr_v4"

        local prefix="${NETWORK##*/}"
        local auto_netmask
        auto_netmask=$(cidr_to_netmask "$prefix")
        local range
        range=$(suggest_range "$NETWORK")
        local auto_range_start="${range% *}"
        local auto_range_end="${range#* }"
        local auto_gateway
        auto_gateway=$(suggest_gateway "$NETWORK")

        echo ""
        print_info "Auto-derived from /${prefix}:"
        print_info "  Netmask:    ${auto_netmask}"
        print_info "  Gateway:    ${auto_gateway}"
        print_info "  Range:      ${auto_range_start} - ${auto_range_end}"
        echo ""

        prompt_value "Netmask" "$auto_netmask" "NETMASK" "validate_netmask"
        prompt_value "Default gateway" "$auto_gateway" "GATEWAY" "validate_ipv4"
        prompt_value "DHCP range start" "$auto_range_start" "RANGESTART" "validate_ipv4"
        prompt_value "DHCP range end" "$auto_range_end" "RANGEEND" "validate_ipv4"

    elif [[ "$IPVERSION" == "6" ]]; then
        prompt_value "Subnet (CIDR notation, e.g. fd12:100:100:40::/64)" "" "NETWORK" "validate_cidr_v6"
    fi

    # --- Step 4: Services ---
    echo ""
    print_header "Step 4: Services"
    echo ""

    if [[ "$IPVERSION" == "4" ]]; then
        prompt_value "DNS nameserver" "" "NAMESERVER" "validate_ipv4"
    else
        prompt_value "DNS nameserver" "" "NAMESERVER" "validate_ipv6"
    fi

    echo ""
    echo -e "  ${DIM}Tip: Enter ${YELLOW}cloud${DIM} to use Arista's cloud redirector${RESET}"
    prompt_value "CV-CUE server address" "" "CVCUE"

    if [[ "$IPVERSION" == "4" ]]; then
        local default_match="ARISTA-AP*"
    else
        local default_match="ARISTA-AP-C-*"
    fi
    prompt_value "VCI match pattern" "$default_match" "MATCHSTRING"

    if [[ "$IPVERSION" == "4" ]]; then
        echo ""
        print_info "Optional: TFTP server for CCS/DCS device boot (leave empty to skip)"
        prompt_value "TFTP server" "" "TFTP" "" "false"
    fi

    # --- Resolve cloud shortcut ---
    if [[ "$CVCUE" == "cloud" ]]; then
        export CVCUE="redirector.online.spectraguard.net"
    fi

    # --- Summary ---
    print_summary

    echo -en "  ${BOLD}Proceed?${RESET} ${DIM}[Y/n]${RESET}: "
    read -r confirm
    if [[ "$confirm" =~ ^[Nn] ]]; then
        echo ""
        print_warn "Aborted."
        exit 0
    fi
    echo ""
}

# ──────────────────────────────────────────────
# Flag Parsing
# ──────────────────────────────────────────────
MODE="generate"
INTERACTIVE=false

if [[ $# -eq 0 ]]; then
    INTERACTIVE=true
fi

while [[ $# -gt 0 ]]; do
    case $1 in
        -devicetype | --devicetype )
            export TYPE="$2"
            shift 2 ;;
        -ipversion | --ipversion )
            export IPVERSION="$2"
            shift 2 ;;
        -network | --network )
            export NETWORK="$2"
            shift 2 ;;
        -range-begin | --range-begin )
            export RANGESTART="$2"
            shift 2 ;;
        -range-end | --range-end )
            export RANGEEND="$2"
            shift 2 ;;
        -netmask | --netmask )
            export NETMASK="$2"
            shift 2 ;;
        -gateway | --gateway )
            export GATEWAY="$2"
            shift 2 ;;
        -nameserver | --nameserver )
            export NAMESERVER="$2"
            shift 2 ;;
        -cvcue | --cvcue )
            export CVCUE="$2"
            shift 2 ;;
        -mode | --mode )
            MODE="$2"
            shift 2 ;;
        -interface | --interface )
            INTERFACE="$2"
            shift 2 ;;
        -matchstring | --matchstring )
            export MATCHSTRING="$2"
            shift 2 ;;
        -tftp | --tftp )
            export TFTP="$2"
            shift 2 ;;
        -i | --interactive )
            INTERACTIVE=true
            shift ;;
        -h | --help )
            show_help ;;
        * )
            print_error "Unknown option: $1"
            echo -e "  Run ${CYAN}$0 --help${RESET} for usage information."
            exit 1 ;;
    esac
done

# ──────────────────────────────────────────────
# Interactive or flag-driven
# ──────────────────────────────────────────────
if [[ "$INTERACTIVE" == true ]]; then
    interactive_setup
fi

# ──────────────────────────────────────────────
# Resolve cloud shortcut (flag mode)
# ──────────────────────────────────────────────
if [[ "$CVCUE" == "cloud" ]]; then
    export CVCUE="redirector.online.spectraguard.net"
fi

# ──────────────────────────────────────────────
# Input Validation (flag mode)
# ──────────────────────────────────────────────
if [[ -z "$IPVERSION" ]]; then
    print_error "IP version is required (-ipversion 4|6)"
    echo -e "  Run ${CYAN}$0 --help${RESET} or ${CYAN}$0 --interactive${RESET}"
    exit 1
fi

# ──────────────────────────────────────────────
# Test Mode
# ──────────────────────────────────────────────
if [[ "$MODE" == "test" ]]; then
    if [[ -z "$INTERFACE" ]]; then
        print_error "Test mode requires -interface"
        exit 1
    fi
    print_header "Testing DHCP and DNS"
    if ! command -v dhclient &>/dev/null; then
        print_error "dhclient is required. Install with: apt install isc-dhcp-client"
        exit 1
    fi
    print_success "dhclient found"

    if [[ "$IPVERSION" == "4" ]]; then
        print_header "DNS Lookup"
        nslookup "wifi-security-server"

        print_header "DHCP Test on ${INTERFACE}"
        timeout 5 tcpdump -c 2 -v -nni "$INTERFACE" port 68 and port 67 &
        timeout 5 dhclient -cf "${SCRIPT_DIR}/isc_dhcp_ap_client.conf" -d -v -sf /bin/true -lf /tmp/test.leases "$INTERFACE" 2>/dev/null

        if [[ -n "$CVCUE" ]]; then
            print_header "CV-CUE Connectivity"
            nc -zv "$CVCUE" 3851
        fi
    fi
    if [[ "$IPVERSION" == "6" ]]; then
        print_warn "IPv6 testing is not yet implemented."
    fi
    exit 0
fi

# ──────────────────────────────────────────────
# Auto-derive defaults & validate (generate/install)
# ──────────────────────────────────────────────
if [[ "$IPVERSION" == "4" ]]; then
    DHCPCONFIG="/etc/dhcp/dhcpd.conf"

    if [[ -n "$NETWORK" ]]; then
        local_prefix="${NETWORK##*/}"

        if [[ -z "$NETMASK" ]]; then
            NETMASK=$(cidr_to_netmask "$local_prefix")
            export NETMASK
        fi
        if [[ -z "$GATEWAY" ]]; then
            GATEWAY=$(suggest_gateway "$NETWORK")
            export GATEWAY
        fi
        if [[ -z "$RANGESTART" || -z "$RANGEEND" ]]; then
            range=$(suggest_range "$NETWORK")
            [[ -z "$RANGESTART" ]] && export RANGESTART="${range% *}"
            [[ -z "$RANGEEND" ]]   && export RANGEEND="${range#* }"
        fi
    fi

    if [[ -z "$MATCHSTRING" ]]; then
        export MATCHSTRING="ARISTA-AP*"
    fi

    missing=()
    [[ -z "$NETWORK" ]]    && missing+=("-network")
    [[ -z "$NETMASK" ]]    && missing+=("-netmask")
    [[ -z "$GATEWAY" ]]    && missing+=("-gateway")
    [[ -z "$RANGESTART" ]] && missing+=("-range-begin")
    [[ -z "$RANGEEND" ]]   && missing+=("-range-end")
    [[ -z "$NAMESERVER" ]] && missing+=("-nameserver")
    [[ -z "$CVCUE" ]]      && missing+=("-cvcue")

    if [[ ${#missing[@]} -gt 0 ]]; then
        print_error "Missing required options: ${missing[*]}"
        echo -e "  Run ${CYAN}$0 --help${RESET} for usage information."
        exit 1
    fi

    validate_cidr_v4 "$NETWORK"  || { print_error "Invalid IPv4 CIDR: $NETWORK"; exit 1; }
    validate_ipv4 "$NAMESERVER"  || { print_error "Invalid IPv4 nameserver: $NAMESERVER"; exit 1; }
    validate_ipv4 "$GATEWAY"     || { print_error "Invalid IPv4 gateway: $GATEWAY"; exit 1; }
    validate_ipv4 "$RANGESTART"  || { print_error "Invalid IPv4 range-begin: $RANGESTART"; exit 1; }
    validate_ipv4 "$RANGEEND"    || { print_error "Invalid IPv4 range-end: $RANGEEND"; exit 1; }
    validate_netmask "$NETMASK"  || { print_error "Invalid netmask: $NETMASK"; exit 1; }
fi

if [[ "$IPVERSION" == "6" ]]; then
    DHCPCONFIG="/etc/dhcp/dhcpd6.conf"

    if [[ -z "$MATCHSTRING" ]]; then
        export MATCHSTRING="ARISTA-AP-C-*"
    fi

    missing=()
    [[ -z "$NETWORK" ]]     && missing+=("-network")
    [[ -z "$NAMESERVER" ]]  && missing+=("-nameserver")
    [[ -z "$CVCUE" ]]       && missing+=("-cvcue")

    if [[ ${#missing[@]} -gt 0 ]]; then
        print_error "Missing required options: ${missing[*]}"
        echo -e "  Run ${CYAN}$0 --help${RESET} for usage information."
        exit 1
    fi

    export MAGICSTRING
    MAGICSTRING=$(python3 "${SCRIPT_DIR}/isc_dhcp6_generate_option17.py" "$CVCUE")
fi

# ──────────────────────────────────────────────
# Generate Mode
# ──────────────────────────────────────────────
if [[ "$MODE" == "generate" ]]; then
    ISCCONFIG=$(generate_config)
    print_header "Generated ISC DHCP Configuration"
    echo -e "${DIM}─────────────────────────────────────────────${RESET}"
    echo "$ISCCONFIG"
    echo -e "${DIM}─────────────────────────────────────────────${RESET}"
    print_success "Config printed to stdout. Copy the content above into ${CYAN}${DHCPCONFIG}${RESET}"
fi

# ──────────────────────────────────────────────
# Install Mode
# ──────────────────────────────────────────────
if [[ "$MODE" == "install" ]]; then
    ISCCONFIG=$(generate_config)

    print_header "Install Mode"

    if ! grep -q Ubuntu /etc/os-release 2>/dev/null; then
        print_error "Install mode is only supported on Ubuntu."
        exit 1
    fi
    print_success "Ubuntu detected"

    if ! command -v dhcpd &>/dev/null; then
        print_error "isc-dhcp-server is not installed. Run: apt install isc-dhcp-server"
        exit 1
    fi
    print_success "isc-dhcp-server found"

    if ! ip route get "$GATEWAY" &>/dev/null; then
        print_error "No interface in the target subnet. Ensure this server has an IP in ${NETWORK}."
        exit 1
    fi
    print_success "Interface reachable in target subnet"

    echo ""
    echo -e "${DIM}─────────────────────────────────────────────${RESET}"
    echo "$ISCCONFIG"
    echo -e "${DIM}─────────────────────────────────────────────${RESET}"
    echo ""
    print_warn "This will overwrite ${CYAN}${DHCPCONFIG}${RESET} and restart isc-dhcp-server."
    echo -en "  ${BOLD}Proceed?${RESET} ${DIM}[y/N]${RESET}: "
    read -r confirm
    if [[ ! "$confirm" =~ ^[Yy] ]]; then
        print_warn "Aborted."
        exit 0
    fi

    echo "$ISCCONFIG" | tee "$DHCPCONFIG" > /dev/null
    systemctl restart isc-dhcp-server.service
    print_success "Configuration written and isc-dhcp-server restarted."
    systemctl status isc-dhcp-server.service --no-pager -l
fi
