!
hostname BENEDIKT-CCS-710XP
!
username admin privilege 15 secret arista
!
vrf instance MGMT
!
ip routing vrf MGMT
!
interface Management1
   vrf MGMT
   dhcp client accept default-route
   ip address dhcp
   no shutdown
!
! 5. Activate Management Services in the VRF
management api http-commands
   no shutdown
   vrf MGMT
      no shutdown
!
management ssh
   vrf MGMT
      no shutdown
!
zerotouch disable
!
end