option space arista;
option arista.cv-cue-server code 1 = text;
option arista.magic-string code 4 = text;

class "Arista-AP" {
    match if option vendor-class-identifier ~= "${MATCHSTRING}";
    vendor-option-space arista;
    option arista.cv-cue-server "${CVCUE}";
    option arista.magic-string "SPECTRATALK";
}
