configure terminal
!
router bgp 65000
   router-id 192.168.51.3
   !
   neighbor 192.168.51.250 remote-as 65000
   neighbor 192.168.51.250 description "ExaBGP Full Table Injector"
   neighbor 192.168.51.250 send-community
   !
   address-family ipv4
      neighbor 192.168.51.250 activate
      neighbor 192.168.51.250 maximum-routes 1200000 warning-only
   !
   address-family ipv6
      neighbor 192.168.51.250 activate
      neighbor 192.168.51.250 maximum-routes 500000 warning-only
   !
end
write memory
