process fullbgp {
    # Make sure to update this path to where your actual script is located
    run /usr/bin/python3 /home/benedikt/Network-Toolkit/exabgp/fullbgptable.py;
    encoder text;
}

neighbor 192.168.51.3 {
    router-id 192.168.51.250;
    local-address 192.168.51.250;
    local-as 65000;
    peer-as 65000;

    api {
        processes [ fullbgp ];
    }
}
